#!/usr/bin/env bash
# install ngix server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me 301 Moved Permanently;' /etc/nginx/sites-available/default
sudo service nginx reload
sudo service nginx start
