#!/usr/bin/env bash
# install ngix server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
server {
   listen 80;
   server_name example.com;

   location /redirect_me {
   	return 301 https://example.com/new_location;
   }
 }

